"""Tests for the advisory claimed-IOC fact-verification pass (plan #10)."""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "revai"))

import report_quality as rq  # noqa: E402


REPORT = """## 8. Indicators of Compromise

- C2: hxxp[:]//evil-c2[.]biz/gate.php (source: yara)
- IP: 203.0.113.10 (source: floss)
- Domain: benign-update[.]microsoft[.]com (source: strings)
- SHA256: 5f4dcc3b5aa765d61d8327deb882cf995f4dcc3b5aa765d61d8327deb882cf99
- Key: HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run
- Contact: bad@evil-c2.biz
"""

EVIDENCE = """
urls: hxxp[:]//evil-c2[.]biz/gate.php
ips: 203.0.113.10
registry: HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run
strings: contact bad@evil-c2.biz for instructions
"""


def test_verifies_present_and_flags_absent():
    result = rq.verify_claimed_iocs(REPORT, EVIDENCE)
    assert result["advisory"] is True
    values = {i["value"] for i in result["unverified_items"]}
    # The invented hash is not in the evidence and must be flagged.
    assert "5f4dcc3b5aa765d61d8327deb882cf995f4dcc3b5aa765d61d8327deb882cf99" in values
    assert result["verified"] >= 3
    assert result["excluded"] >= 1  # vendor/telemetry domain


def test_benign_domain_is_excluded_not_unverified():
    result = rq.verify_claimed_iocs(REPORT, EVIDENCE)
    reasons = [i["reason"] for i in result["excluded_items"]]
    assert any("vendor" in r for r in reasons)
    assert all("microsoft" not in i["value"] for i in result["unverified_items"])


def test_empty_inputs_are_safe():
    result = rq.verify_claimed_iocs("", "")
    assert result["claims"] == 0
    assert result["unverified_items"] == []


PROV = "52d7c4523f5df47cc6baf2666b407788a2b1cf9a"


def test_provenance_commit_is_excluded_not_unverified():
    """Rehearsal regression (2026-09-21): the provenance banner carries the
    pipeline commit (64-hex) — build metadata, not a sample indicator."""
    banner = REPORT + (
        f"\n> **RevAI provenance** — commit `{PROV}` · engine langgraph\n"
    )
    result = rq.verify_claimed_iocs(banner, EVIDENCE, provenance_commit=PROV)
    assert all(i["value"] != PROV for i in result["unverified_items"])
    reasons = [i["reason"] for i in result["excluded_items"]]
    assert any("provenance" in r for r in reasons)


def test_provenance_commit_from_env(monkeypatch):
    monkeypatch.setenv("REVAI_COMMIT", PROV)
    result = rq.verify_claimed_iocs(REPORT + f"\ncommit `{PROV}`\n", EVIDENCE)
    assert all(i["value"] != PROV for i in result["unverified_items"])
    reasons = [i["reason"] for i in result["excluded_items"]]
    assert any("provenance" in r for r in reasons)


def test_other_64hex_hashes_are_still_flagged():
    # The exclusion is limited to the pipeline's own commit; an unrelated
    # 64-hex claim must still be reported unverified.
    result = rq.verify_claimed_iocs(REPORT, EVIDENCE, provenance_commit=PROV)
    values = {i["value"] for i in result["unverified_items"]}
    assert "5f4dcc3b5aa765d61d8327deb882cf995f4dcc3b5aa765d61d8327deb882cf99" in values


def test_report_banner_commit_from_an_earlier_deploy_is_excluded():
    """A report generated by an older pipeline commit stays clean after redeploy."""
    old = "efad0742fcfaca13f69797c74aed850e4273bb9d"
    md = (f"> **RevAI provenance** — commit `{old}` · engine `langgraph`\n"
          "No sample indicator of note in this line (source: se).\n")
    result = rq.verify_claimed_iocs(md, "", provenance_commit=PROV)
    assert result["unverified"] == 0
    assert any(i["value"] == old for i in result["excluded_items"])


def test_documentation_ips_are_excluded():
    """RFC 5737/loopback placeholders are not claims about the sample."""
    result = rq.verify_claimed_iocs("Example: 192.0.2.123 and 127.0.0.1.", "")
    assert result["unverified"] == 0
    assert result["excluded"] == 2


def test_fenced_code_placeholders_are_not_claims():
    """A code snippet with a placeholder hash is an illustration, not a claim."""
    md = ("## 9. Indicators of Compromise\n\n"
          "```python\n"
          'pe.imphash() == "5f2c4f85f614392e3d2e4f6a8b7c9d0e"  # placeholder, compute actual\n'
          "```\n\n"
          "No indicators were established.\n")
    result = rq.verify_claimed_iocs(md, "")
    assert result["unverified"] == 0
    # The same hash in prose is still a claim and must be flagged.
    result2 = rq.verify_claimed_iocs("MD5: 5f2c4f85f614392e3d2e4f6a8b7c9d0e", "")
    assert result2["unverified"] == 1


def test_canonical_run_key_target_is_excluded_but_observed_verifies():
    run = r"HKCU\Software\Microsoft\Windows\CurrentVersion\Run"
    unobserved = ("| File (registry) | RegSetValue under "
                  f"{run} (or equivalent) | not observed in 10.5 s window |")
    result = rq.verify_claimed_iocs(unobserved, "")
    assert result["unverified"] == 0
    assert any("canonical persistence template" in i["reason"]
               for i in result["excluded_items"])
    # If a tool did observe the key, the evidence match verifies it normally.
    result2 = rq.verify_claimed_iocs(unobserved, f"procmon: {run} -> value Foo")
    assert result2["verified"] == 1
    # A sample-specific key is still a claim and must be verifiable.
    result3 = rq.verify_claimed_iocs(r"Key: HKCU\Software\ZProtect\Run", "")
    assert result3["unverified"] == 1


def test_collect_evidence_text_reads_known_files(tmp_path):
    (tmp_path / "deep_dive").mkdir()
    (tmp_path / "deep_dive" / "01-tools-raw.json").write_text('{"a": "evil-c2.biz"}')
    (tmp_path / "iocs.json").write_text('{"domains": ["evil-c2[.]biz"]}')
    text, used = rq.collect_evidence_text(tmp_path)
    assert "evil-c2.biz" in text
    assert any("01-tools-raw.json" in u for u in used)
    assert any("iocs.json" in u for u in used)
    assert "REPORT" not in text


def test_collect_evidence_text_is_bounded(tmp_path):
    (tmp_path / "iocs.json").write_text("x" * 5000)
    text, _used = rq.collect_evidence_text(tmp_path, max_bytes=1000)
    assert len(text) <= 1000


def _write_winre_pack(winre_root, sha, dns):
    dyn = winre_root / sha / "static" / "dynamic"
    dyn.mkdir(parents=True)
    (dyn / "META.json").write_text(json.dumps({"ok": True}))
    (dyn / "network_intel.json").write_text(json.dumps({
        "captures": [{"dns_queries": dns, "tls_sni": [], "http_requests": []}]}))
    (dyn / "frida_summary.json").write_text(json.dumps({"decoded_paths": []}))


def test_dynamic_pack_iocs_verify(tmp_path, monkeypatch):
    """A report citing the dynamic block's IoCs verifies against the pack."""
    sha = "b" * 64
    case = tmp_path / sha
    case.mkdir()
    winre_root = tmp_path / "winre-logs"
    monkeypatch.setenv("REVAI_WINRE_LOGS", str(winre_root))
    # No pack yet -> the dynamic-only domains are unverified (presence gating).
    md = "DNS: `talonstamed.com` and `pywolwnvd.biz` observed."
    text, _used = rq.collect_evidence_text(case)
    assert rq.verify_claimed_iocs(md, text)["unverified"] == 2
    # With the pack, the same claims are backed by raw evidence.
    _write_winre_pack(winre_root, sha, ["talonstamed.com", "pywolwnvd.biz"])
    text, used = rq.collect_evidence_text(case)
    res = rq.verify_claimed_iocs(md, text)
    assert res["unverified"] == 0
    assert any("winre:" in u for u in used)


# --- artifact exclusions + promotion --------------------------------------


def test_generic_hive_keys_are_excluded():
    md = "Persistence via HKEY_CURRENT_USER\\Run and HKLM\\Run."
    result = rq.verify_claimed_iocs(md, "")
    assert result["unverified"] == 0
    assert result["excluded"] == 2
    assert all("specific subkey" in i["reason"] for i in result["excluded_items"])


def test_benign_url_host_is_excluded():
    md = "Namespace: http://xml.org/schemas/xml/lexical-handler"
    result = rq.verify_claimed_iocs(md, "")
    assert result["unverified"] == 0
    assert result["excluded"] >= 1


def test_prose_identifiers_are_not_claims():
    md = "The `powershell.exe` path uses capability.attack.execution telemetry."
    result = rq.verify_claimed_iocs(md, "")
    assert result["claims"] == 0


def test_ioc_factcheck_issue_modes(monkeypatch):
    monkeypatch.delenv("REVAI_IOC_FACTCHECK", raising=False)
    assert rq._ioc_factcheck_issue({"unverified": 2}) == "report:unverified_iocs:2"
    assert rq._ioc_factcheck_issue({"unverified": 0}) is None
    monkeypatch.setenv("REVAI_IOC_FACTCHECK", "advisory")
    assert rq._ioc_factcheck_issue({"unverified": 2}) is None

# --- behavior prerequisites (#14d) ----------------------------------------
#
# Calibration 2026-09-27 (56-case published corpus) REJECTED promotion to a
# blocking gate; the check stays advisory. These tests pin the fixed classifier,
# a positive control, and the three real false-positive classes the calibration
# found (see tests/test_behavior_prereq_calibration.py for the full set).

MD_CLAIM = "The sample performs process injection and establishes persistence."
MD_DENIAL = "There is no registry manipulation and no process injection in this sample."


def test_claim_without_supporting_api_is_uncorroborated_not_unsupported():
    """Absence from a curated import map is not evidence of absence."""
    surface = "createremotethread\nwriteprocessmemory"  # injection only
    result = rq.verify_behavior_prerequisites(MD_CLAIM, surface)
    assert result["advisory"] is True
    assert result["uncorroborated"] == 1          # persistence has no API here
    assert result["unsupported"] == 0             # ... and that is NOT a gate failure


def test_claim_with_supporting_api_is_not_flagged():
    surface = "createremotethread\nregsetvalueex"
    result = rq.verify_behavior_prerequisites(MD_CLAIM, surface)
    assert result["unsupported"] == 0
    assert result["uncorroborated"] == 0
    assert result["checked"] == 2


def test_contradiction_is_detected_positive_control():
    """The detector CAN fire: a denial whose behaviour the map shows."""
    surface = "createservice\nopenscmanager"
    md = "The sample does not use persistence mechanisms."
    result = rq.verify_behavior_prerequisites(md, surface)
    assert result["unsupported"] == 1
    assert result["contradictions"][0]["behavior"] == "persistence"
    assert "createservice" in result["contradictions"][0]["present"]


def test_contradiction_does_not_fail_the_gate():
    """The decision under test: advisory stays advisory, so issues stay clean."""
    surface = "createservice\nopenscmanager"
    md = "The sample does not use persistence mechanisms."
    result = rq.verify_behavior_prerequisites(md, surface)
    assert result["advisory"] is True
    assert "promotion" in result and "rejected" in result["promotion"]


def test_corroborated_absence_is_not_a_contradiction():
    """A denial the evidence agrees with (ghyte: pe_imports signal_count 0)."""
    md = "There are no registry-based persistence mechanisms in this sample."
    result = rq.verify_behavior_prerequisites(md, "")   # empty import map
    assert result["unsupported"] == 0
    assert result["negated_mentions"] >= 1


def test_packed_sample_reads_incomplete():
    result = rq.verify_behavior_prerequisites(MD_CLAIM, "", packed=True)
    assert result["analysis_incomplete"] is True
    assert result["packed"] is True
    assert result["unsupported"] == 0


def test_empty_report():
    result = rq.verify_behavior_prerequisites("", "anything")
    assert result["checked"] == 0
    assert result["unsupported_items"] == []


def test_collect_import_surface_reads_the_high_signal_map(tmp_path):
    (tmp_path / "pe-imports.txt").write_text(
        '{"engine": "pe_imports", "signal_count": 2,'
        ' "signals": [{"api_match": "CreateRemoteThread"},'
        ' {"api_match": "RegSetValueExA"}]}')
    surface, sources = rq.collect_import_surface(tmp_path)
    assert "createremotethread" in surface
    assert "regsetvalueexa" in surface
    assert sources == ["pe-imports.txt"]


def test_collect_import_surface_reads_the_bare_list_shape(tmp_path):
    (tmp_path / "pe-imports.txt").write_text(
        '[{"api_match": "CreateServiceA", "attack": ["T1543"]}]')
    surface, _ = rq.collect_import_surface(tmp_path)
    assert "createservicea" in surface


def test_collect_import_surface_rejects_capa_titles(tmp_path):
    """The noise filter: finding titles are not API names (was 0/27 usable)."""
    (tmp_path / "pe-imports.txt").write_text(
        '{"engine": "pe_imports", "signals": [{"api_match": "RegSetValueExA"}]}')
    (tmp_path / "quick_scan").mkdir()
    (tmp_path / "quick_scan" / "00-tools-raw.json").write_text(
        '{"top_rules": [{"name": "encrypt data using rc4 prga"},'
        ' {"name": ".text"}, {"name": "gdi32.OFT"}]}')
    surface, _ = rq.collect_import_surface(tmp_path)
    assert "regsetvalueexa" in surface
    assert "encrypt data using rc4 prga" not in surface
    assert ".text" not in surface


def test_collect_import_surface_falls_back_to_structured(tmp_path):
    (tmp_path / "quick_scan").mkdir()
    (tmp_path / "quick_scan" / "00-tools-raw.json").write_text(
        '{"pe_imports": {"signals": [{"api_match": "CreateRemoteThread"}]}}')
    surface, sources = rq.collect_import_surface(tmp_path)
    assert "createremotethread" in surface
    assert any("00-tools-raw.json" in s for s in sources)
