name=CADRE
description=Custom PE loader that ensures external references are created for PE import tables, including embedded PEs in binder/dropper files.
author=CADRE RE Team
createdOn=07/16/2026
version=1.0.0
